"""traces and escalations

Written by hand rather than autogenerated: autogenerate proposes dropping the
generated `text_search` column and its indexes, because the ORM deliberately does
not declare a column the database maintains itself.
"""

import sqlalchemy as sa
from alembic import op

revision = "0002"
down_revision = "0001"


def upgrade() -> None:
    op.create_table(
        "traces",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("question", sa.Text, nullable=False),
        sa.Column("answer", sa.Text, nullable=False),
        sa.Column("escalated", sa.Boolean, nullable=False),
        sa.Column("reason", sa.String(64), nullable=True),
        sa.Column("top_score", sa.Float, nullable=False),
        sa.Column("margin", sa.Float, nullable=False),
        sa.Column("retrieved", sa.JSON, nullable=False),
        sa.Column("input_tokens", sa.Integer, nullable=False),
        sa.Column("output_tokens", sa.Integer, nullable=False),
        sa.Column("cost_usd", sa.Float, nullable=False),
        sa.Column("model", sa.String(128), nullable=False),
        sa.Column("prompt_version", sa.String(64), nullable=False),
        sa.Column("latency_ms", sa.Integer, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "escalations",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column(
            "trace_id",
            sa.Integer,
            sa.ForeignKey("traces.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("question", sa.Text, nullable=False),
        sa.Column("reason", sa.String(64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )


def downgrade() -> None:
    op.drop_table("escalations")
    op.drop_table("traces")
